type: deployment
image:
  repository: registry.vn/ecommerce/minimal-service
  tag: PIPELINE-TEST-888
  pullPolicy: IfNotPresent
deployment:
  replicas: 1
  containerPort: 8080
  resources: {}
  strategy:
    type: RollingUpdate
  securityContext:
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    capabilities:
      drop:
      - ALL
  imagePullSecrets:
  - name: regcred
  envFrom:
  - configMapRef:
      name: ecommerce-config
  env: []
  volumes:
  - name: tmp
    emptyDir: {}
  volumeMounts:
  - name: tmp
    mountPath: /tmp
  affinity: {}
serviceAccount:
  create: false
  name: default
service: {}
ingress: {}
pvc: {}
localConfig:
  enabled: false
