type: deployment
image:
  repository: registry.vn/test/full-app
  tag: null
  pullPolicy: IfNotPresent
deployment:
  replicas: 3
  containerPort: 9000
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  strategy:
    type: RollingUpdate
  securityContext:
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 2000
    runAsGroup: 1000
    capabilities:
      drop:
      - ALL
  imagePullSecrets:
  - name: regcred
  livenessProbe: null
  readinessProbe: null
  env:
  - name: APP_MODE
    value: production
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: multi-apps-test-secret
        key: DATABASE_PASSWORD
  - name: API_TOKEN
    valueFrom:
      secretKeyRef:
        name: multi-apps-test-secret
        key: API_TOKEN
  - name: DOMAIN
    valueFrom:
      configMapKeyRef:
        name: multi-apps-test-config
        key: DOMAIN
  volumes:
  - name: custom-data
    emptyDir: {}
  volumeMounts:
  - name: custom-data
    mountPath: /data
  affinity: {}
serviceAccount:
  create: false
  name: default
service: {}
ingress:
  enabled: true
  host: full.example.com
  annotations:
    kubernetes.io/ingress.class: nginx
genConfigMaps: true
