type: deployment
image:
  repository: registry.vn/ecommerce/api-gateway
  tag: latest
  pullPolicy: IfNotPresent
deployment:
  replicas: 1
  containerPort: 80
  resources: {}
  strategy:
    type: RollingUpdate
  securityContext:
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    capabilities:
      drop:
      - ALL
  imagePullSecrets:
  - name: regcred
  envFrom:
  - configMapRef:
      name: ecommerce-config
  - configMapRef:
      name: external-global-config
  env: []
  volumes:
  - name: tmp
    emptyDir: {}
  volumeMounts:
  - name: tmp
    mountPath: /tmp
  affinity: {}
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3
    httpGet:
      path: /
      port: 80
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3
    httpGet:
      path: /
      port: 80
serviceAccount:
  create: false
  name: default
service:
  type: ClusterIP
  port: 80
  targetPort: 80
ingress:
  enabled: true
  hosts:
  - host: api.example.com
    paths:
    - path: /
      pathType: ImplementationSpecific
      servicePort: 80
pvc: {}
localConfig:
  enabled: false
