type: deployment
image:
  repository: registry.vn/ecommerce/api-gateway
  tag: PIPELINE-TEST-888
  pullPolicy: IfNotPresent
deployment:
  replicas: 2
  containerPort: 80
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  strategy:
    type: RollingUpdate
  securityContext:
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    capabilities:
      drop:
      - ALL
  imagePullSecrets:
  - name: regcred
  envFrom:
  - configMapRef:
      name: ecommerce-config
  env: []
  volumes:
  - name: tmp
    emptyDir: {}
  volumeMounts:
  - name: tmp
    mountPath: /tmp
  affinity: {}
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3
    tcpSocket:
      port: 80
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3
    tcpSocket:
      port: 80
serviceAccount:
  create: false
  name: default
service:
  type: ClusterIP
  port: 80
  targetPort: 80
ingress:
  enabled: true
  path: /
  hosts:
  - host: api.example.com
    paths:
    - path: /
      pathType: ImplementationSpecific
      servicePort: 80
pvc: {}
localConfig:
  enabled: false
