type: deployment
image:
  repository: registry.vn/ecommerce/redis-proxy
  tag: latest
  pullPolicy: IfNotPresent
deployment:
  replicas: 1
  containerPort: 6379
  resources: {}
  strategy:
    type: RollingUpdate
  securityContext:
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    capabilities:
      drop:
      - ALL
  imagePullSecrets:
  - name: regcred
  envFrom:
  - configMapRef:
      name: ecommerce-config
  env: []
  volumes:
  - name: tmp
    emptyDir: {}
  - name: data-volume
    persistentVolumeClaim:
      claimName: '{{ include "common-lib.fullname" . }}'
  volumeMounts:
  - name: tmp
    mountPath: /tmp
  - name: data-volume
    mountPath: /data
  affinity: {}
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3
    tcpSocket:
      port: 6379
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3
    tcpSocket:
      port: 6379
serviceAccount:
  create: false
  name: default
service: {}
ingress: {}
pvc:
  enabled: true
  size: 5Gi
  mountPath: /data
  accessModes:
  - ReadWriteOnce
localConfig:
  enabled: false
