type: deployment
image:
  repository: registry.vn/payment-service
  tag: latest
  pullPolicy: IfNotPresent
deployment:
  replicas: 2
  containerPort: 8082
  resources: {}
  strategy:
    type: RollingUpdate
  securityContext:
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: false
    runAsNonRoot: false
    runAsUser: 0
    capabilities:
      drop:
      - ALL
  env: []
  volumes: []
  volumeMounts: []
  affinity: {}
serviceAccount:
  create: false
  name: ''
service:
  enabled: true
  port: 80
ingress:
  enabled: true
  className: my-cloud-alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
  hosts:
  - host: payment.my-platform.com
    paths:
    - path: /api/v1/pay
