type: deployment
image:
  repository: registry.vn/ecommerce/payment-service
  tag: latest
  pullPolicy: IfNotPresent
deployment:
  replicas: 1
  containerPort: 9090
  resources: {}
  strategy:
    type: RollingUpdate
  securityContext:
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    capabilities:
      drop:
      - ALL
  imagePullSecrets:
  - name: regcred
  envFrom:
  - configMapRef:
      name: ecommerce-config
  env: []
  volumes:
  - name: tmp
    emptyDir: {}
  volumeMounts:
  - name: tmp
    mountPath: /tmp
  affinity: {}
serviceAccount:
  create: false
  name: default
service:
  type: NodePort
  port: 80
  targetPort: 9090
  nodePort: 30005
ingress: {}
pvc: {}
localConfig:
  enabled: false
