apiVersion: v2
name: minimal-service
description: Chart for minimal-service
type: application
version: 0.1.0
dependencies:
- name: common-lib
  version: 1.0.0
  repository: file://../../../../../helm-templates/common-lib
  alias: common-lib
